# Use postgres/example user/password credentials
version: '3.3'

services:

  web:
    build:
      context: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=example
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
      - 8000:5000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    expose:
      - 5432
